### ISSUE TITLE
ScrollablePositionedList.builder. itemBuilder index == -1

### ISSUE THREAD

**Issue by liqping** [google/flutter.widgets#104]
when itemCount == List.length 
  if the list is empty ( Don't add element on initState()),in future, change the number of list, index will return -1;   example code will print 
       flutter: index:-1
  if the list is not empty, it's ok; example code will print 
         flutter: index:0
         flutter: index:0
        flutter: index:1
        flutter: index:2
        flutter: index:3

/// example code

List selectStatus = [];
void initState() {
    // TODO: implement initState
    super.initState();

   selectStatus.add(false);  /// if  comment the line  ,will print index:-1
    Future.delayed(Duration(seconds: 1),()
    {
      setState(() {
        selectStatus.add(false);
        selectStatus.add(false);
        selectStatus.add(false);
      });
    });
}

ScrollablePositionedList.builder(
        itemBuilder: (context, int index) {
          print('index:$index');
          return  Container(height: 50,color: Color(Random().nextInt(0xffffff)+0xff000000),);
        },
        itemCount: selectStatus.length,
      )

**Comment by vasilich6107** [comment]
Added PR to fix this)

**Comment by maksumon** [comment]
@jamesderlin This PR is not yet added with the package installer, is it? I installed the package last night and still getting that index = -1 issue.

**Comment by jamesderlin** [comment]
@maksumon If you look at https://github.com/google/flutter.widgets/pull/106, you can see that it has not been reviewed and merged yet.

**Comment by maksumon** [comment]
@jamesderlin Ah, yes, thanks for the update...

**Comment by tarobins** [comment]
Looking at pr now
