### ISSUE TITLE
build widget keeps firing

### ISSUE THREAD

**Issue by boucoding** [google/flutter.widgets#116]
Hi,

I am using this awesome plugin but I have found an issue while I am using it inside a video player widget in order to know what video is currently playing which is that as mentioned in the title the build method keeps firing and this affects the video player which cant be controlled.

Hope you find a solution.

wish you a good day

thanks

**Comment by jamesderlin** [comment]
This GitHub repository includes multiple packages.  What package are you referring to?  It would help a lot if you could provide sample code (ideally a minimal, complete, verifiable example) that can reproduce the problem that you are encountering.

**Comment by boucoding** [comment]
I am sorry, I mean visibility detector widget, you can reproduce it by playing a video with chewie player in any listview

**Comment by jamesderlin** [comment]
Can you please provide code that can reproduce the problem?

**Comment by boucoding** [comment]
please feel free to run this project to reproduce the error
https://github.com/boucoding/visibility_detector_video_player_bug_sample

**Comment by jamesderlin** [comment]
In your sample code, you have:

```dart
VisibilityDetector(
  Key('${DateTime.now()}${context.hashCode}'),
  ...
```
Every time your `build` method is called, it will use a different `Key`, destroying the old `VisibilityDetector` and creating a new one.  That triggers the `onVisibilityChanged` callback, leading the video constantly being paused and resumed.

The `VisibilityDetector` should have a key that is persistent for the lifetime of the `VisibilityDetector`.

**Comment by boucoding** [comment]
Sorry for wasting your time,

Thank you,

happy coding
