### ISSUE TITLE
Failed assertion: line 195 pos 12: '_scrollableListState != null': is not true.

### ISSUE THREAD

**Issue by dbmartin00** [google/flutter.widgets#122]
## Problem description
On destroying a scrollable list view, I get the failed assertion detailed below.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
'package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart': Failed assertion: line 195 pos 12: '_scrollableListState != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ItemScrollController._detach (package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart:195:12)
#3      _ScrollablePositionedListState.dispose (package:flutter_widgets/src/scrollable_positioned_list/src/scrollable_positioned_list.dart:232:34)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435:12)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746:7)
...

## Steps to reproduce

```

import 'package:flutter/material.dart';
import 'package:flutter_icons/flutter_icons.dart';
import 'package:flutter_widgets/flutter_widgets.dart';
import 'package:split2go/SplitRestHelper.dart';
import 'MetricTile.dart';
import 'NameIdTuple.dart';
import 'NamedTuples.dart';


class MetricTilePage extends StatelessWidget {
  static const routeName = '/metrics';

  @override
  Widget build(BuildContext context) {
    final List<MetricTile> arg = ModalRoute.of(context).settings.arguments;

    return  Scaffold(
      appBar: AppBar(
        title: Text("Behold your Metrics"),
      ),
      body: Center(
        child: MetricTileListView(arg),
      ),
    );
  }
}


class MetricTileListView extends StatelessWidget {
  final ItemScrollController _scrollController = ItemScrollController();

  final List<MetricTile> tiles = List();
  final List<Icon> icons = List();

  MetricTileListView(List<MetricTile> arg) {
    this.tiles.addAll(arg);
    tiles.forEach((tile) {
      if(tile.pValue != null && tile.pValue < 0.05) {
        if(tile.positive) {
          icons.add(Icon(Icons.check_circle, color: Colors.green));
        } else {
          icons.add(Icon(Icons.warning, color: Colors.red));
        }
      }
      else {
        icons.add(Icon(Icons.sync, color: Colors.yellow));
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return ScrollablePositionedList.separated(
      itemScrollController: _scrollController,
      itemCount: tiles.length,
      separatorBuilder: (context, index) {
        return Divider(
            thickness: 5,
            color: Colors.black
        );
      },
      itemBuilder: (context, index) {
        return Container(
          decoration: new BoxDecoration(
              color: Colors.white70
          ),
          child: ListTile(
            title:
            Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget> [
                  Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: <Widget> [
                        Text(tiles[index].name),
                        icons[index]
                      ]
                  ),
                  Text(tiles[index].formula, style: TextStyle(fontSize: 10, fontStyle: FontStyle.italic))
                ]),
            contentPadding: EdgeInsets.all(5),
            onTap: () { },
          ),
        );
      },
    );
  }
}
```

## Environment
flutter_widgets: ^0.1.12

## Additional details
I saw this failed assertion reported earlier, but I am not using a State instance to implement an initState method for initializing the scroller.

All my experiments with changing how it is initialized have failed to resolve the assertion.

**Comment by steve-cahn** [comment]
Did you find a fix to this yet? I have the exact issue

**Comment by jamesderlin** [comment]
This assert was removed in May 2020 by 87c2c15d2bb3ebd9743ba5dd118bcbabd32a0f9b.

@steve-cahn If you are still encountering this, please update to a newer version of `ScrollablePositionedList`.  Note that `package:flutter_widgets` is deprecated (the last version being 0.1.12); please use `package:scrollable_positioned_list` instead.
