### ISSUE TITLE
Index getting skipped while scrolling

### ISSUE THREAD

**Issue by sanalkv** [google/flutter.widgets#124]
## Problem description
Listener skips few indexes while scrolling.

while scrolling im getting wrong indexes.
(ItemPosition(index: 7, itemLeadingEdge: -0.1668520578420467, itemTrailingEdge: 0.05116796440489433), ItemPosition(index: 12, itemLeadingEdge: 0.9232480533926585, itemTrailingEdge: 1.1412680756395996), ItemPosition(index: 11, itemLeadingEdge: 0.7052280311457174, itemTrailingEdge: 0.9232480533926585), ..., ItemPosition(index: 9, itemLeadingEdge: 0.26918798665183535, itemTrailingEdge: 0.4872080088987764), ItemPosition(index: 8, itemLeadingEdge: 0.05116796440489433, itemTrailingEdge: 0.26918798665183535)).

While scrolling in a particular position, the listener returns a same value continuously and then skips few indexes and return another value.

**Comment by FernandoUFS** [comment]
I have same issue here. Because of that it's not smooth. I'm using Axis.horizontal.

**Comment by andreystavitsky** [comment]
Same issue. Seems like that happens when ScrollablePositionedList rebuild already built items

**Comment by andreystavitsky** [comment]
Seems like itemPositionsListener.itemPositions.value.first.index give wrong item sometimes, and correct way is
```
int currentItem = itemPositionsListener.itemPositions.value
          .where((ItemPosition position) => position.itemTrailingEdge > 0)
          .reduce((ItemPosition min, ItemPosition position) =>
              position.itemTrailingEdge < min.itemTrailingEdge ? position : min)
          .index;
```

**Comment by sanalkv** [comment]
@andreystavitsky The above solution worked perfectly, i hope its not a workaround because I'am deploying this code in production. Thanks again.

**Comment by andreystavitsky** [comment]
@sanalkv this solution is from official example [(link)](https://github.com/google/flutter.widgets/blob/4838a698ba7e21d3087adef460530ad441a4031b/packages/scrollable_positioned_list/example/lib/scrollable_positioned_list_example.dart#L123), so it's seems to be safe to use in production. Anyway it's definitely not an obvious (neither elegant) way to use this widget.

**Comment by sanalkv** [comment]
Alright, Thanks for the update.

**Comment by DucTrungNguyen** [comment]
@andreystavitsky thanks, i have fixed

**Comment by cabba** [comment]
I stumbled upon this behavior also in version `0.3.8`. I've fixed using the patch proposed by @andreystavitsky but there is any chance that this issue gets fixed in a future release?
