### ISSUE TITLE
ItemPositionsListener notify nothing after itemCount set zero

### ISSUE THREAD

**Issue by kazu0620** [google/flutter.widgets#136]
## Problem description
It's problem of scrollable_positioned_list. If build ScrollablePositionedList with zero itemCount, ItemPositionsListener notify nothing even if the list rebuild with non-zero itemCount.

The problem seems like fixed in this PR: https://github.com/google/flutter.widgets/pull/109 , but hasn't yet included to the latest master.

## Steps to reproduce
1. Build ScrollablePositionedList with zero itemCount and enable itemPositionsListener.
2. Rebuild ScrollablePositionedList with non zero itemCount.
3. Even if you scroll the list, the itemPositionsListener are notified nothing.

I have reproduced the problem in this repo with minimum code.
https://github.com/kazu0620/positions_listener_probelm/blob/master/lib/main.dart

## Additional details
When itemCount is zero, registeredElements.value will be null in the following code. The problem is that return without changing updateScheduled.

https://github.com/google/flutter.widgets/blob/master/packages/scrollable_positioned_list/lib/src/positioned_list.dart#L307

Since updateScheduled is still true after return, next update will never scheduled.

**Comment by mx1up** [comment]
any updates on this?

**Comment by kazu0620** [comment]
This issue Fixed by https://github.com/google/flutter.widgets/pull/184/
