### ISSUE TITLE
onVisibilityChanged is not returning data when widget fully visible

### ISSUE THREAD

**Issue by bibash28** [google/flutter.widgets#142]
VisibilityDetector(
                          key: key1,
                          onVisibilityChanged: (VisibilityInfo info) {
                            print(info.visibleFraction.toString()); print("1");
                          },
                          child: View1()
                        ),
                        VisibilityDetector(
                          key: key2,
                          onVisibilityChanged: (VisibilityInfo info) {
                            print(info.visibleFraction.toString()); print("2");
                          },
                          child: View2()
                        ),
                        VisibilityDetector(
                          key: key3,
                          onVisibilityChanged: (VisibilityInfo info) { 
                            print(info.visibleFraction.toString()); print("3");
                          },
                          child: View3()
                        ),

Package Used: visibility_detector 0.1.5

Consider that I have three views(View1, View2, View3) in a vertical list.

When I scroll and when there is a situation in a screen
View 1: 30%
View 2: 100%
View 3: 23%

Output:
1
3

In such situation 2 is not printed which means that onVisibilityChanged is not responding if 100% widget is shown.

**Comment by jamesderlin** [comment]
The `onVisibilityChanged` callback will be triggered only when visibility *changes*.  It should be triggered the first time a widget becomes visible.  If the widget is already 100% visible and remains 100% visible, it will not be triggered again.

Can you clarify what you're observing?  That is, are you saying that `onVisibilityChanged` is not being called for "View 2" when it was *not* 100% visible and then becomes 100% visible?

**Comment by bibash28** [comment]
Hey James,

Thank you for your response. 
No, onVisibilityChanged is called for "View 2" when it is not 100% visible but not called when it is 100% visible.

My use case is to detect the widgets that has 100% visibility in screen.

I hope this explains. Thanks a lot.

**Comment by jamesderlin** [comment]
Sorry, that's still not clear.  Again, I specifically want to know: when "View 2" *changes* from being partially visible to being 100% visible, are you saying that `onVisibilityChanged` is not called?

The example application *does* report widgets that are 100% visible.  Can you reproduce your problem in that?

**Comment by bibash28** [comment]
Consider a screen height of 100.
Container1 with height 40
Container 2 with height 40
Container3 with height 40
I have three containers in a list.

Now,when I scroll and make the following scenario
Container1 20% visible
Container2 100% visible
Container3 15% visible

Here invisibliltyChanged is called for container1 and container3. It means that when container2 is 100%, invisibliltyChanged is not called.

**Comment by jamesderlin** [comment]
As I've explained, `onVisibilityChanged` only fires when visibility *changes*.

In the scenario you described, initially Container 1 has 100% visibility, Container 2 has 100% visibility, and Container 3 is 50% visible.  When all of these widgets *first* became visible, their `onVisibilityChanged` callbacks should have fired to report their *initial* visibilities.

When you scroll, Container 2's visibility does not change: it started at 100% and remains at 100%.  It is expected that its `onVisibilityChanged` callback does not execute in that case.

**Comment by bibash28** [comment]
Is there anyway you can help with to achieve the visibility of widget in current screen?

**Comment by jamesderlin** [comment]
You can keep track of the last known visibility for each widget yourself.  Whenever you get an `onVisibilityChanged` callback, if the visibility is non-zero, store the key and the visibility in a `Map`.  If the visibility is 0, remove the key from the `Map`.  Then you can query the `Map` to retrieve the last known visibility for a widget whenever you want.

**Comment by bibash28** [comment]
Thanks a lot. I will keep that in mind...Thank you for your valuable time...
