### ISSUE TITLE
Offline cannot work

### ISSUE THREAD

**Issue by DipakSkywave** [google/flutter.widgets#152]
Does this dependency work offline?

  final ItemScrollController itemScrollController = ItemScrollController();

ScrollablePositionedList.builder(
  itemCount: list.length,
 itemBuilder: (context, index) {return _method(homeList, index);              },
  itemScrollController: itemScrollController,
  itemPositionsListener: itemPositionsListener,
);

  itemScrollController.scrollTo(index: index, duration: Duration(milliseconds: 1));

Error : 
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:scrollable_positioned_list/src/scrollable_positioned_list.dart': Failed assertion: line 192 pos 12: '_scrollableListState != null': is not true.

**Comment by jamesderlin** [comment]
If you're asking if `ScrollablePositionedList` should work on a device without an Internet connection, then yes.  Network connectivity shouldn't be involved at all.  What makes you think that it is?

If you're encountering a problem, a minimal, complete reproduction case would help a lot.
