### ISSUE TITLE
Hope for flutter_simple_treeview adds the function of modifying icon widget and location

### ISSUE THREAD

**Issue by zhaolinlins** [google/flutter.widgets#166]

**Comment by polina-c** [comment]
Can you, clarify, please?
Under 'icon' do you mean the icon to expand/collapse a node? 
What options would you suggest for location?

**Comment by zhaolinlins** [comment]
> Can you, clarify, please?
> Under 'icon' do you mean the icon to expand/collapse a node?
> What options would you suggest for location?

Yes, it is.

For example, it can be put to the right

**Comment by polina-c** [comment]
Interesting. Can you provide a mock how would it look like?

(i am going to vacation and will be silent till Aug 17)

**Comment by polina-c** [comment]
closing as an icon or any other widget can be rendered as part of the node
