### ISSUE TITLE
ScrollablePositionedList: Laggy problem when including a StreamBuilder in the construction of the Index

### ISSUE THREAD

**Issue by oseiasmribeiro** [google/flutter.widgets#181]
## Problem description
I tested it on devices, Redmi Note 7 and Iphone 8, as well as emulators. I noticed that if I put any StreamBuilder in the index, both in ListView.Builder and in ScrollablePositionList the Laggy problem happens. If I remove it goes back to normal. This gets to be a big hassle, because if the user is reading a book the possibility of getting lost in the paragraphs is very large. In my case when I'm rolling down, it doesn't happen, but when I roll up, it gets to skip paragraphs. I don't know if it is correct to say that you cannot use StreamBuilder inside the ScrollablePositionList, because if I remove everyone who is inside the problem is solved. Once again I emphasize that this happens with ListView.Builder too.

## Code example
https://drive.google.com/file/d/13e0obso6KfjsW1rElH3ne4-APFVXiWj4/view?usp=sharing

## Video example
https://drive.google.com/file/d/1Nb9T0adSUi1tWA9MJNqu2S-KlLMcMGh9/view?usp=sharing

## Environment
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[✓] Connected device (1 available)

• No issues found!
oseiasribeiro@Oseiass-MBP busca-flutter % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.7 19H2, locale pt-BR)
    • Flutter version 1.20.4 at /Users/oseiasribeiro/Downloads/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/oseiasribeiro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 55711D46-E166-420B-8491-9E3D8D677C7F • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!`

**Comment by oseiasmribeiro** [comment]
As before, removing all StreamBuilders from within the ScrollablePositionedList the problem is solved. Follow the sample code. I will leave it open for possible analysis and closing of the problem.
https://drive.google.com/file/d/18TLZgX3b5c9gq2z2i89UtZLPX19cMgoe/view?usp=sharing

**Comment by mwolffalonso** [comment]
Hello, after i upgraded to Flutter 1.22 the position has gone crazy. I mean sometimes it hits the correct item but most of the time it does not. I am also using StreamBuilder, in fact i need it as i am receiving events from other plugins through streams and i use them as the trigger to change the position. So i cant move away from StreamBuilder, at least not easily.
I downgraded back Flutter to 1.20.3 and the problem isn't there. 
There are no error messages or exceptions in the log.
Appreciate your help. Thanks!

**Comment by oseiasmribeiro** [comment]
It seems that we have 2 distinct problems: One with the use of StreamBuilder and the other with Flutter 1.22. See #179

**Comment by tarobins** [comment]
As I mentioned in the other issue, if someone has a link to a  repo that demos the problem, that's be really helpful.

I watched the video, but I had trouble following what was happening vs supposed to happen.

**Comment by mwolffalonso** [comment]
Hello Tom, 

Will share an example in short. 

Thanks, 
Martin. 

----- Mensaje original -----

De: "Tom Robinson" <notifications@github.com> 
Para: "google/flutter.widgets" <flutter.widgets@noreply.github.com> 
CC: "mwolffalonso" <martin.wolff@vera.com.uy>, "Comment" <comment@noreply.github.com> 
Enviados: Viernes, 9 de Octubre 2020 0:17:12 
Asunto: Re: [google/flutter.widgets] ScrollablePositionedList: Laggy problem when including a StreamBuilder in the construction of the Index (#181) 





As I mentioned in the other issue, if someone has a link to a repo that demos the problem, that's be really helpful. 

I watched the video, but I had trouble following what was happening vs supposed to happen.

**Comment by oseiasmribeiro** [comment]
@tarobins Follow the repository link so you can see the problem that exists when I involve StreamBuilder within the construction of the index: [https://github.com/oseiasmribeiro/scrollablepositionedlistlag.git](https://github.com/oseiasmribeiro/scrollablepositionedlistlag.git)
I created 2 widgets ReadingMessage () is where the problem happens and ReadingMessageNotBug () is where the problem does not happen. To test, just change the comment bars. This part of code is inside the file ReadingMessage.dart. See the example below:

> ...
class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: ReadingMessage(),
      //home: ReadingMessageNotBug(),
    );
  }
}
...

**Comment by tarobins** [comment]
Ok, I was able to repo your issue with your example code, so thanks for passing that along.  I'll look more tomorrow for the cause of the issue; it's past my bedtime.

**Comment by tarobins** [comment]
FWIW, something that worries me is the use of the `_fontSize` var and setting that from several different builders.  Seems like things could get out of sync.  To simplify things, I'd recommend:

1. Replace Streams/Sink and StreamBuilders with ValueListenable/ValueNotifier and ValueListenableBuilder.  This will make it more clear that you're trying to sync a value across several parts of your app rather than caring about the history of the value.  
2. get rid of `_fontSize` and only ever read from the value passed to the `builder` closure.  

I'm not sure this will solve the problem, but it'll reduce the chance of things getting out of sync.

**Comment by oseiasmribeiro** [comment]
@tarobins  Thank you very much, if you can give me an example of how to remove `_fontSize` and only ever read from the value passed to the builder closure.

**Comment by oseiasmribeiro** [comment]
Remember that you have two widgets, one with and one without the problem. What does not have a problem is commented with bars, example::
```
home: ReadingMessage (),
// home: ReadingMessageNotBug (),
```

**Comment by tarobins** [comment]
So one thing I noticed is if I added a log as in https://github.com/tarobins/scrollablepositionedlistlag/commit/a37f956a83db8968c9309f1f3d2cf319114b4ab2 and I scroll, I get

```
I/flutter ( 1546): Building with null
I/chatty  ( 1546): uid=10100(com.example.scrollablepositionedlistlag) 1.ui identical 42 lines
I/flutter ( 1546): Building with null
I/flutter ( 1546): Building with 22.0
I/chatty  ( 1546): uid=10100(com.example.scrollablepositionedlistlag) 1.ui identical 42 lines
I/flutter ( 1546): Building with 22.0
I/flutter ( 1546): Building with null
I/flutter ( 1546): Building with 22.0
...
```

I don't expect you want to build with a font size of null, I don't know why that's happening, and I don't know the consequence, but that's possibly causing some issues.

**Comment by tarobins** [comment]
Also, here's a version where I removed _fontSize https://github.com/tarobins/scrollablepositionedlistlag/commit/dd3da08cf0deb52dc111fb30b2e795cd3671cb14

Will try a few more things tomorrow to simplify the code and try to figure out what's going, but maybe look into that null issue.

**Comment by tarobins** [comment]
@oseiasmribeiro  Ok, here's a version that I think is working better.  Please give it a try and let me know if you can still repo https://github.com/tarobins/scrollablepositionedlistlag/commits/switch_to_value

**Comment by oseiasmribeiro** [comment]
> Also, here's a version where I removed _fontSize [tarobins/scrollablepositionedlistlag@dd3da08](https://github.com/tarobins/scrollablepositionedlistlag/commit/dd3da08cf0deb52dc111fb30b2e795cd3671cb14)
> 
> edit -> but now I maybe see why you are using _fontSize.

@tarobins This really is a big question about using StreamBuilder, its first return is always null, so I use the condition:
```
if (snapshotOutValueFontSize.data == null) {
   return Center(child: CircularProgressIndicator());
}
```
Really, the idea of using ValueListenableBuilder it really is very valid.

**Comment by oseiasmribeiro** [comment]
> @oseiasmribeiro Ok, here's a version that I think is working better. Please give it a try and let me know if you can still repo https://github.com/tarobins/scrollablepositionedlistlag/commits/switch_to_value
> 
> (make sure you try the switch_to_value branch)

@tarobins With ValueListenableBuilder it was really quite satisfactory. Thanks for the great help, for teaching and for your time. I'm very grateful. I will update my entire project.

**Comment by oseiasmribeiro** [comment]
> So one thing I noticed is that if I added a log as in [tarobins/scrollablepositionedlistlag@a37f956](https://github.com/tarobins/scrollablepositionedlistlag/commit/a37f956a83db8968c9309f1f3d2cf319114b4ab2) and I scroll, I get
> 
> ```
> I/flutter ( 1546): Building with null
> I/chatty  ( 1546): uid=10100(com.example.scrollablepositionedlistlag) 1.ui identical 42 lines
> I/flutter ( 1546): Building with null
> I/flutter ( 1546): Building with 22.0
> I/chatty  ( 1546): uid=10100(com.example.scrollablepositionedlistlag) 1.ui identical 42 lines
> I/flutter ( 1546): Building with 22.0
> I/flutter ( 1546): Building with null
> I/flutter ( 1546): Building with 22.0
> ...
> ```
> 
> I don't expect you want to build with a font size of null, I don't know why that's happening, and I don't know the consequence, but that's possibly causing some issues.
> 
> edit -> oh I guess the null builds is why you're reading from _fontSize
