### ISSUE TITLE
ItemPositionsListener does not work when starting from empty list

### ISSUE THREAD

**Issue by mx1up** [google/flutter.widgets#182]
## Problem description
package: scrollable_positioned_list
When starting off with an empty list and later putting some items in it, ItemPositionsListener does not work. 
This issue is probably related with PR #109 , #156 , #136 , maybe #88 

## Steps to reproduce
Test case: https://github.com/mx1up/flutter.widgets/commit/308278da6d24d4b0add623bff31f8ec181605681

## Expected behavior
ItemPositionsListener to work

## Actual behavior
ItemPositionsListener does nothing

## Environment
Flutter 1.20.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 840c9205b3 (9 weeks ago) • 2020-08-04 20:55:12 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
scrollable_positioned_list 0.1.7

## Additional details
Tested in test framework, android and web

**Comment by tarobins** [comment]
@mx1up I have a fix.  But in order to add your test to the code, I need you to sign the CLA.  https://cla.developers.google.com/clas  can you please do so?

**Comment by tarobins** [comment]
fwiw, the fix is to change [this line](https://github.com/google/flutter.widgets/blob/master/packages/scrollable_positioned_list/lib/src/positioned_list.dart#L307) to 

```
        if (registeredElements.value == null) {
          updateScheduled = false;
          return;
        };
```

**Comment by mx1up** [comment]
hi @tarobins , that is awesome! thank you. I signed the CLA. Should I create a new pull request with my tests? you may have noticed I also wrote a test case that did not exhibit the bug (not starting from an empty model). I wrote it to validate my test was written correctly ;) should I include it as well? : https://github.com/mx1up/flutter.widgets/commit/34a84c009d3140f3e8b881b32ab401fe302c52f2

**Comment by tarobins** [comment]
@mx1up  Thanks!

No need to create a PR.  I have to manually copy the change into our internal repo first, and I've already done that.

Also, I just need the breaking test.  (While trying the test, I temporarily modified it to start with a non-empty list as well just to check what happened.)

**Comment by mx1up** [comment]
ok, clear :+1:
