### ISSUE TITLE
IOS stop scrolling when the last item appear on screen

### ISSUE THREAD

**Issue by moosalim** [google/flutter.widgets#202]
There is an issue with ios only, the scrolling keep working even if the last item is visible on the screen. 

there is no such issue in android, is it working perfectly

**Comment by omchiii** [comment]
same problem here

**Comment by omchiii** [comment]
> There is an issue with ios only, the scrolling keep working even if the last item is visible on the screen.
> 
> there is no such issue in android, is it working perfectly

ListView(
  physics: ClampingScrollPhysics(),
)

This did it for me. The overscroll effect comes from BouncingScrollPhysics added by ScrollBehavior.

credits: https://stackoverflow.com/questions/58645048/how-to-remove-overscroll-on-ios

**Comment by nesara-cmd** [comment]
postcss.parse

**Comment by jamesderlin** [comment]
I assume that this issue is about `ScrollablePositionedList`?  The issue template provides specific instructions to describe which package you're filing an issue about.

**Comment by jamesderlin** [comment]
It sounds like this is working as intended and isn't specific to `ScrollablePositionedList`.
