### ISSUE TITLE
[flutter_simple_treeview] The performance is too weak.

### ISSUE THREAD

**Issue by 6643** [google/flutter.widgets#204]
I've got about `20*20*20` entries.
It takes a long time to render.
Can you replace Column with ListView.builder?

**Comment by polina-c** [comment]
I like the suggestion.
If you can share your example it would help with the fix validation.

**Comment by 6643** [comment]
sorry
It's my own fault.
Incorrect array design leads to huge computations
It's not that the rendering is too slow.
sorry
sorry
sorry
