### ISSUE TITLE
ScrollablePositionedList scrolling up jumps and oscillates with async builder

### ISSUE THREAD

**Issue by smartyboy** [google/flutter.widgets#224]
### Problem description
My project has elements of unpredictable height in the ScrollablePositionedList. Elements are fetched on demand from local database (still async). The only way I know to feed async data to list's lazy builder is using FutureBuilder. 
It seems to me that elements (above the visible area) are being built when scrolling up, as follows: first the FutureBuilder builds a placeholder with some guessed height and then replaces it with real data (real height which seems to be the reason for the jumps).
It oscillates (repeated jumps) when rolling over exact same position, seems like its rebuilding the same element immediately due to the jump (again putting in a smaller placeholder and then inflating it with real data).

Maybe there is a better way for async builder and surely the writers of the lib must have thought about it, but for the time being I consider this jumping behaviour as a bug.

![t6](https://user-images.githubusercontent.com/7578609/106064474-9904f580-6102-11eb-9eda-4e17e2f3a64d.gif)
Please ignore the right-to-left swipe in the end.

### Code for reproduction
```
import 'package:flutter/material.dart';
import 'package:scrollable_positioned_list/scrollable_positioned_list.dart';
import 'dart:math';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<int> heights = [];

  @override
  void initState() {
    super.initState();
    Random random = new Random();
    for (int i = 0; i < 500; i++) heights.add(random.nextInt(100) + 30);
  }

  Future<int> fetchElement(int index) async {
    await Future.delayed(Duration(seconds: 0));
    return heights[index];
  }

  Widget itemBuilder(BuildContext context, int index) {
    Future<int> element = fetchElement(index);
    return FutureBuilder<int>(
      future: element,
      builder: ((context, snapshot) {
        if (snapshot.connectionState == ConnectionState.done)
          return Container(
              color: index % 5 == 0 ? Colors.amber : Colors.white,
              height: snapshot.data.toDouble(),
              child: Text("Index $index, ${snapshot.data}"));
        return Container(height: 5, child: CircularProgressIndicator());
      }),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ScrollablePositionedList.builder(
          itemCount: heights.length, itemBuilder: itemBuilder),
    );
  }
}
```
Scroll down a few screens and start scrolling up slowly.

#### Expected behavior
Scrolling up should be smooth, just as scrolling down is, elements on screen must follow the finger

#### Actual behavior
While scrolling up the view makes abrupt jumps (above it some element gets its true height), sometimes keeps oscillating.

#### Environment
  scrollable_positioned_list: ^0.1.9
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.14.6 18G6032 darwin-x64) 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)

**Comment by Umar1312** [comment]
@smartyboy Have you been able to fix this issue? Have the same one too

**Comment by smartyboy** [comment]
@Umar1312 I found [huge_listview](https://github.com/deakjahn/huge_listview) which is just a wrapper around scrollable_positioned_list. I implemented similar caching to get rid of Future (i still have some errors but i guess i can figure them out).

**Comment by mwolffalonso** [comment]
I think this issue i opened might be related to this one

https://github.com/google/flutter.widgets/issues/222

**Comment by smartyboy** [comment]
@mwolffalonso this is reproducible with 1.20.4.
Flutter (Channel unknown, 1.20.4, on Mac OS X 10.14.6 18G6032). Tested on iOS.

This issue has nothing to do with flutter versions - its a design choice of how element adding is handled inside SPL.
Though I think it should be possible to handle inflating objects above the view without visible jumps, but there are some higher priority issues on SPL...
I will close this issue since caching solves it for me as mentioned above.

**Comment by PaulRudin** [comment]
I'm not sure that this should be closed really - it seems like there's a bug that still exists, whether or not there's a workaround?

**Comment by PaulRudin** [comment]
And incidentally, I can get the same behaviour with a large enough list when scrolling down too. If you scroll up fast for quite a long way, and then scroll down slowly you get the same sort of thing.
