### ISSUE TITLE
Migrate scrollable_positioned_list to null-safety

### ISSUE THREAD

**Issue by ikicodedev** [google/flutter.widgets#227]
## Problem description
scrollable_positioned_list is not migrated to null-safety

## Steps to reproduce
I have tried migrating my package to null-safety but it depends on scrollable_positioned_list

![image](https://user-images.githubusercontent.com/5318708/108198549-0f05e680-711c-11eb-882e-17460ba167df.png)

**Comment by jamesderlin** [comment]
Fixed with 6cdc1ff.
