### ISSUE TITLE
Flutter 2.0 tagged_text error mediaquery.of

### ISSUE THREAD

**Issue by moreirawebmaster** [google/flutter.widgets#236]
1 warning generated.
    ../../../.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.12/lib/src/tagged_text/tagged_text.dart:295:36: Error: No named parameter with the name 'nullOk'.
                MediaQuery.of(context, nullOk: true)?.textScaleFactor ??
                                       ^^^^^^
    flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
      static MediaQueryData of(BuildContext context) {
                            ^^

**Comment by jamesderlin** [comment]
I'm sorry to inform you that `tagged_text` was removed a year ago and is no longer supported.

(The `flutter_widgets` package itself is deprecated; most of its widgets instead have been moved into their own individual packages, although `tagged_text` is not among them.  Refer to the [last update to flutter_widget's README](https://pub.dev/packages/flutter_widgets).)

**Comment by jamesderlin** [comment]
If you wish to continue using `tagged_text`, you can modify your own copy to remove its usage of the defunct `nullOk` parameter.  See https://docs.google.com/document/d/1LKBL0S1uyhACDiUXILhLKFZH8Cpl_w3mXjHgaE8_--U/edit
