### ISSUE TITLE
visibility_detector Migrate to null safety 

### ISSUE THREAD

**Issue by kw2019ltd** [google/flutter.widgets#237]
https://dart.dev/null-safety/migration-guide#step1-wait

**Comment by jlnrrg** [comment]
It looks to me that the [package](https://github.com/google/flutter.widgets/blob/master/packages/visibility_detector/pubspec.yaml) itself is already migrated, but has yet to be published to pub.dev

**Comment by jamesderlin** [comment]
Uh, visibility_detector 0.2.0-nullsafety.1 has been on pub.dev [since January](https://pub.dev/packages/visibility_detector/versions#prerelease).

**Comment by jlnrrg** [comment]
great work, and sorry for wasting your time. :see_no_evil: 
It was my bad for not checking twice as my `dart pub outdated --mode=null-safety` did not list the according version.
