### ISSUE TITLE
Scroll index is out of bounds.

### ISSUE THREAD

**Issue by ROCKWAR** [google/flutter.widgets#238]
## Problem description
using package: **scrollable_positioned_list**
When I use initialscrollindex or jumpTo, which aims near the end of the items, I jump the error: Scroll index is out of bounds, in the debug console. 

## Steps to reproduce
1. For this I have used the example that is on the scrollable_positioned_list page, and I have compiled it with Visual Studio Code.  [https://pub.dev/packages/scrollable_positioned_list/example](url)
2. the first constant (5001), I have changed it by 105, so as not to have as many items.
3. Then in the application that is running, I have pressed in the row of "Jump to", the number 100, obviously near the end of all the items (they are 105 items) 

## Expected behavior
If you show me the desired item, but I throw me on the debug console: E / AccessibilityBridge (8809): Scroll Index is out of bounds.

## Environment
I use: Windows 10, Visual Studio Code, smartphone: Motorola G9 plus.

## Additional details
It seems to me that the problem lies when I want to go to any item that originates that the last item is shown, and no longer can be scrolled. Because if you jump to an item that does not show the last item, there is no problem.

**Comment by RedFox64** [comment]
I have the same problem

**Comment by HarsHvA** [comment]
@ROCKWAR  did you get any solution?

**Comment by owl352** [comment]
I have a solution, but unfortunately I can't show it. I've lost the logical line of code.
But I can tell you how to solve this problem.
res:
1. [ItemPositionsListener](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/ItemPositionsListener-class.html)
2. [itemPositions](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/ItemPositionsListener/itemPositions.html)
3. [ItemPosition](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/ItemPosition-class.html)

```
             if(maxElementsOnScreen==0.0){
                maxElementsOnScreen = itemPositionsListener.itemPositions.value.length;
              }

              if(maxElementsOnScreen-1<symbIndex||lastIndex>(maxElementsOnScreen/2).round()){
                listController.jumpTo(index: indexInList);
              }else{
                listController.scrollTo(index: items.length-maxElementsOnScreen+1,duration: Duration(milliseconds: 100));
              }
            
```

In this code, we check whether the variable is `maxElementsOnScreen` empty (since the type is double, then 0.0). Then we equate it to the maximum number of elements on the screen (for this we use `ItemPositionsListener`). Then we can check the position of the element. If it is at the end of the list, then scroll to the element (total elements)-(maximum of elements)+-1 element.
it works for me.

**Comment by owl352** [comment]
> I have a solution, but unfortunately I can't show it. I've lost the logical line of code. But I can tell you how to solve this problem. res:
> 
> 1. [ItemPositionsListener](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/ItemPositionsListener-class.html)
> 2. [itemPositions](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/ItemPositionsListener/itemPositions.html)
> 3. [ItemPosition](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/ItemPosition-class.html)
> 
> ```
>              if(maxElementsOnScreen==0.0){
>                 maxElementsOnScreen = itemPositionsListener.itemPositions.value.length;
>               }
> 
>               if(maxElementsOnScreen-1<symbIndex||lastIndex>(maxElementsOnScreen/2).round()){
>                 listController.jumpTo(index: indexInList);
>               }else{
>                 listController.scrollTo(index: items.length-maxElementsOnScreen+1,duration: Duration(milliseconds: 100));
>               }
>             
> ```
> 
> In this code, we check whether the variable is `maxElementsOnScreen` empty (since the type is double, then 0.0). Then we equate it to the maximum number of elements on the screen (for this we use `ItemPositionsListener`). Then we can check the position of the element. If it is at the end of the list, then scroll to the element (total elements)-(maximum of elements)+-1 element. it works for me.

I prescribed it so that the last elements create a spring effect (this is the +-1 element)


https://user-images.githubusercontent.com/64574305/165343351-05f6b8da-313d-4c5c-bbaf-99013be80556.mp4

**Comment by owl352** [comment]
resolve #238

**Comment by owl352** [comment]
Closes #238

**Comment by Anantharao1998** [comment]
I have the same problem

**Comment by GujjuFlutterGuy** [comment]
@ROCKWAR Are you still facing this issue? Or did you fixed it anyway?

**Comment by Shyamaly62** [comment]
Can you please explain the solution in detail?

**Comment by ROCKWAR** [comment]
@Shyamaly62 I remember that I came out in the Android emulator, but in a physical team, it does not come out, in fact this was more than two years ago and I do not come out.
