### ISSUE TITLE
flutter_widgets 0.1.6-dev.1 is incompatible with flutter v1.9.1+hotfix.2

### ISSUE THREAD

**Issue by miguelcmedeiros** [google/flutter.widgets#25]
As a followup of #20 being fixed, I tried upgrade to flutter v1.9.1+hotfix.2 (now beta and I am assuming it will become stable soon), but `pub get` complains that `intl` in flutter sdk (0.15.8) is behind what `flutter_widgets` requires (0.16.0):
```
Because every version of app_ui from path depends on hux from path which depends on flutter_widgets 0.1.6-dev.1, every version of app_ui from path requires flutter_widgets 0.1.6-dev.1.
And because flutter_widgets >=0.1.6-dev.1 depends on intl ^0.16.0 and every version of flutter_localizations from sdk depends on intl 0.15.8, app_ui from path is incompatible with flutter_localizations from sdk.
So, because hue_blue_app depends on app_ui from path which depends on flutter_localizations any from sdk, version solving failed.
pub get failed (1)
```

Is it strictly needed for `flutter_widgets` to use 0.16.0?

**Comment by jamesderlin** [comment]
I made flutter_widgets 0.1.6-dev.1 track the flutter 's`master` branch.  I suppose I should have made it track the `dev` branch instead and not bothered publishing a release for flutter `master`.

**Comment by jamesderlin** [comment]
Actually, I'm not sure why `intl` is even a dependency.

**Comment by miguelcmedeiros** [comment]
@jamesderlin, thanks a lot for the quick reaction!!!
I could upgrade to v1.9.1+hotfix.2 using 0.1.6-dev.2.
