### ISSUE TITLE
type 'double' is not a subtype of type 'ItemPosition' issue while using positioned_list with gridview as Child 

### ISSUE THREAD

**Issue by ChiHwe** [google/flutter.widgets#266]
![image](https://user-images.githubusercontent.com/24539251/119337120-0ac00b00-bcc1-11eb-8014-0c2b070a84db.png)

It throw this error while using gridview in the positionedlist. 

Anyone facing this issue before?

Please help, thanks

**Comment by euriasb** [comment]
Same thing happened to me, it was because I had widget higher up the tree with a `PageStorageKey`, solved by wrapping my `ScrollablePositionedList` on a `PageStorage` widget.

**Comment by ChiHwe** [comment]
> Same thing happened to me, it was because I had widget higher up the tree with a `PageStorageKey`, solved by wrapping my `ScrollablePositionedList` on a `PageStorage` widget.

Thanks! i manage to find the problem and solved it
