### ISSUE TITLE
VisibilityDetector report wrong visibleFraction value

### ISSUE THREAD

**Issue by jiamuc** [google/flutter.widgets#289]
if an alert dialog shown, the visibleFraction  should change, 
but in my test, the visibleFraction not change, it sames that VisibilityDetector can not detect a dialog

**Comment by jamesderlin** [comment]
Can you elaborate?   Can you provide a reproduction case?  Are you talking about visibility of the dialog itself or about a widget behind the dialog?  If the latter, as noted in the documentation:

> The reported `visibleFraction` might not account for overlapping widgets that obscure the `VisbilityDetector`.

**Comment by jiamuc** [comment]
thanks, i just know visibleFraction might not account for overlapping widgets

**Comment by jiamuc** [comment]
> Can you elaborate? Can you provide a reproduction case? Are you talking about visibility of the dialog itself or about a widget behind the dialog? If the latter, as noted in the documentation:
> 
> > The reported `visibleFraction` might not account for overlapping widgets that obscure the `VisbilityDetector`.

thanks, i just know visibleFraction might not account for overlapping widgets.
i want to detect the overlapping widgets,  i want to use this feature to control  videoplayer, when any dialog shown, i want to stop the video, and when there is no any dialog, the video shoud play.

**Comment by Justus-M** [comment]
> > Can you elaborate? Can you provide a reproduction case? Are you talking about visibility of the dialog itself or about a widget behind the dialog? If the latter, as noted in the documentation:
> > > The reported `visibleFraction` might not account for overlapping widgets that obscure the `VisbilityDetector`.
> 
> thanks, i just know visibleFraction might not account for overlapping widgets. i want to detect the overlapping widgets, i want to use this feature to control videoplayer, when any dialog shown, i want to stop the video, and when there is no any dialog, the video shoud play. how can i do use VisbilityDetector?

Did you find a solution? I have the same problem.
