### ISSUE TITLE
VisibilityDetector there are multiple at the same time

### ISSUE THREAD

**Issue by getpu** [google/flutter.widgets#290]
I now have a video playlist, i only show play once video,  whenever the video is relatively small, it's show play multiple, is there any way to show just one???

**Comment by jamesderlin** [comment]
It's really hard for me to understand what you're doing and what problem you're encountering without code.  Can you please provide a minimal reproduction case?

**Comment by getpu** [comment]
@jamesderlin 
https://user-images.githubusercontent.com/21093942/135185578-1b546c96-2912-4402-8a82-9f5421986d0a.mp4

**Comment by jamesderlin** [comment]
A video is not reproducible code.  I can't see how you're using `VisibilityDetector`.  It's not even clear how `VisibilityDetector` is related to your problem.

**Comment by getpu** [comment]
yes, i before use inview list plugin , but in flutter 2.5.1 version this plugin is not work. i think use plugin it replace. maybe i don't understand this plugin very well,  thanks.

**Comment by jamesderlin** [comment]
Once again, please create and provide a minimal, complete example that can reproduce the problem.  I can't do anything with this issue without a way to reproduce your problem.  I can't know exactly what you're doing without seeing your code.

**Comment by getpu** [comment]
> 我现在有一个视频播放列表，我只显示播放一次视频，每当视频相对较小时，它显示播放多次，有什么办法只显示一个吗？？？
