### ISSUE TITLE
Visibility detector not triggered when screen is pushed

### ISSUE THREAD

**Issue by SalishKumar** [google/flutter.widgets#295]
## Problem description
package name= visibility detector
issue: Visibility detector is not triggered 

## Steps to reproduce
1. wrap any widget inside it 
2. then push screen 

## Expected behavior
It should trigger as visibility is effected when screen is pushed
## Actual behavior
It doesn't  trigger when screen is pushed

**Comment by jamesderlin** [comment]
Can you please provide sample code that demonstrates the problem?  It's not clear if you're describing a problem where a `VisibilityDetector` does not fire its callback when it becomes non-visible, when it becomes visible, or both.

**Comment by aytunch** [comment]
We are having the exact same issue
Does `VisibilityDetector` emit 0 visibility when a page is pushed on it?

**Comment by oscarshaitan** [comment]
If I understand correctly your bug is when a new page is pushed ?
I have the same escenario and is working fine. probably the only differences in my code is I'm wating for the result in that view
``
await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => AddFlow(),
      ),
    );
``

But lookign deep in my same case there is another view taht Im not wating is is fully working too

**Comment by Chetan-3110** [comment]
I was also facing this issue while using [page_transition](https://pub.dev/packages/page_transition). I fixed it by replacing it with custom transition effect using `PageRouteBuilder`. I don't have much time to look into the actual issue but anyone can check it out if curious.

Here is the code snippet I used while using that package:
```
PageTransition(
        settings: routeSettings,
        type: PageTransitionType.rightToLeft,
        alignment: Alignment.center,
        duration: Duration(milliseconds: 300),
        child: child,
);
```

P.S: I was using named routes.

**Comment by GoodVibesLab** [comment]
I was having a similar issue when pushing a details screen for an item (how had the same key), which I resolved by using:

`VisibilityDetectorController.instance.forget(Key('your_widget_key'));`

You could try to forget your widget once the new screen is pushed.

**Comment by veloso14** [comment]
I manage to get this to work.
The VisibilityDetectorController.instance.forget(Key('your_widget_key')), did not work.
Nor did the VisibilityDetectorController.instance.refreshNow();

I placed a loading widget and used  await Future.delayed(Duration(milliseconds: 502));....

Not the ideal solution however this worked for me.

**Comment by namnh-0652** [comment]
@SalishKumar How did you bypass this issue?

**Comment by SAGARSURI** [comment]
Use `RouteAware` to detect when a page is pushed or popped
