### ISSUE TITLE
Question: Try to recover the state of ScrollablePositionedList

### ISSUE THREAD

**Issue by rockingdice** [google/flutter.widgets#30]
I want to save the offset for a ScrollablePositionedList and recover it if the state has disposed and init again. 
I noticed there are two parameters to do the jumping, one is the 'index' and the other one is 'alignment'.
And I found there are 'itemLeadingEdge' and 'itemTrailingEdge' in the ItemPosition from the ItemPositionsListener, which are likely the same thing as alignment.
But I'm not sure which one to use. I did some test about it, which makes me more confused.

The first question is about the index. I try to jump to index 0, but the index from the ItemPosition is 6. I don't know if it's an inner variable or not. Can I save it and use it when recovering the List? Like jumpTo(index:6) to recover the actual index 0?

The second question is about alignment. It is  limited from 0.0 to 1.0. I noticed the itemLeadingEdge could be negative so it cannot be used directly. itemTrailingEdge is always positive but it can be more than 1.0. I also noticed that itemTrailingEdge minus itemLeadingEdge is always the same - maybe it represents as the item height?

I tried to use above parameters to do the recover. It seems that I can go to the same offset, but the index is 1 right before the actual index.
I'm currently digging the code deeper to find out what happened, but it would be more helpful to know the idea of these parameters.

Thank you! 

@tarobins

**Comment by rockingdice** [comment]
Okay, after some digging, I think I figured out them.
Each of the ItemPositions could be used to recover the positions. But I cannot provide a negative alignment because it will assert, all I need to do is to find an ItemPosition that the itemLeadingEdge is above zero. Any of them could be used to get the correct offset.

I'll close this issue but if someone is curious about the implementation I'll post it here.

**Comment by tarobins** [comment]
yes, itemLeadingEdge is probably the one you want.  

I'll have to look into alignment not being allowed to be negative.  I intended that to be allowed, but now realize it's not.  https://github.com/google/flutter.widgets/issues/31

**Comment by tarobins** [comment]
I've sent a fix for https://github.com/google/flutter.widgets/issues/31 for review in the internal code review system.  Will take a bit to filter out to github.
