### ISSUE TITLE
Cannot run with sound null safety, because the following dependencies don't support null safety

### ISSUE THREAD

**Issue by elcolie** [google/flutter.widgets#301]
## Problem description
Unable to run `flutter_simple_treeview` because it does not support null safety yet

## Steps to reproduce
Install and render `flutter_simple_treeview`

## Expected behavior
Be able to use library

## Actual behavior
It raises an error at compile time

## Environment
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on macOS 11.6 20G165 darwin-x64, locale en-TH)
    • Flutter version 2.6.0-5.2.pre at /Users/sarit/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (6 weeks ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sarit/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/sarit/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/sarit/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/sarit/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7678000/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • EA48D2D1-93D8-4DF5-A3D3-B317D5988B83 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.54

• No issues found!

## Additional details
OSX 11.6

**Comment by jamesderlin** [comment]
flutter_simple_treeview has had a development version with null-safety support since January 2021: https://pub.dev/packages/flutter_simple_treeview/versions/3.0.0-nullsafety.1

It probably should be pushed as a stable release now, though.

**Comment by polina-c** [comment]
https://github.com/google/flutter.widgets/pull/323
