### ISSUE TITLE
/C:/flutter_windows_2.10.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.12/lib/src/feature_discovery/src/overlay_widgets.dart:248:20: Error: The getter 'subhead' isn't defined for the class 'TextTheme'.  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'

### ISSUE THREAD

**Issue by harshithan1095** [google/flutter.widgets#338]
/C:/flutter_windows_2.10.3-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_widgets-0.1.12/lib/src/feature_discovery/src/overlay_widgets.dart:248:20:
Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart'
 ('/C:/flutter_windows_2.10.3-stable/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
      style: theme.subhead.copyWith(color: Colors.white70),
                   ^^^^^^^

Getting error in flutter sdk files
Please help me to resolve this issue

**Comment by talamaska** [comment]
thanks for reporting the issue. It seems there have been some deprecations in 2.10 that I didn't noticed.
Would you like to make a PR fixing the issue with a backward compatibility? If not you might need to wait for some time until I get to that.

**Comment by jamesderlin** [comment]
Per https://pub.dev/packages/flutter_widgets, the package called "flutter_widgets" has not been supported in 2 years ago and instead was broken up into separate packages.  The feature_discovery widget was removed completely.

**Comment by talamaska** [comment]
oh, :D I thought the issue is in my package
