### ISSUE TITLE
ScrollablePositionedList: Support for ScrollablePositionedList.separated?

### ISSUE THREAD

**Issue by Addictorator** [google/flutter.widgets#34]
Is it possible to get a ScrollablePositionedList equivalent for ListView.separated? Sure, it is possible to optionally build the separator within the itembuilder, but would be a nice feature to have, thanks!

**Comment by tarobins** [comment]
The constructor for separated has been added in google's internal code repo.  It'll be pushed to github, but it'll be a bit due to thanksgiving holidays.
