### ISSUE TITLE
visibility_detector 0.3.0 breaks the build

### ISSUE THREAD

**Issue by alexeyinkin** [google/flutter.widgets#354]
## Steps to reproduce
1. In Android Studio, create a new Flutter project.
2. Add `visibility_detector: ^0.3.0` to `pubspec.yaml`
3. Replace `main.dart` with the following:

```dart
import 'package:flutter/material.dart';
import 'package:visibility_detector/visibility_detector.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: VisibilityDetector(
        key: ValueKey(1),
        child: Scaffold(),
        onVisibilityChanged: (_) {},
      ),
    );
  }
}
```

## Expected behavior
The app builds.

## Actual behavior

```
Launching lib/main.dart on SM T585 in debug mode...
Running Gradle task 'assembleDebug'...
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.3.0/lib/src/visibility_detector_layer.dart:126:37: Error: Property 'renderView' cannot be accessed on 'RendererBinding?' because it is potentially null.
 - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/rendering/binding.dart').
Try accessing using ?. instead.
    assert(RendererBinding.instance.renderView != null);
                                    ^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.3.0/lib/src/visibility_detector_layer.dart:127:59: Error: Property 'renderView' cannot be accessed on 'RendererBinding?' because it is potentially null.
 - 'RendererBinding' is from 'package:flutter/src/rendering/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/rendering/binding.dart').
Try accessing using ?. instead.
    var clipRect = Offset.zero & RendererBinding.instance.renderView.size;
                                                          ^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.3.0/lib/src/visibility_detector_layer.dart:170:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
                                  ^^^^^^^^^^^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.3.0/lib/src/visibility_detector_layer.dart:194:10: Error: Method 'scheduleTask' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        .scheduleTask<void>(_processCallbacks, Priority.touch);
         ^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script '/home/alexey/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/alexey/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by alexeyinkin** [comment]
At https://pub.dev/packages/visibility_detector/score
the score also shows broken static analysis with some of the above errors.

**Comment by alexeyinkin** [comment]
I understand that in Flutter 2.13 all these nullable getters become non-nullable. So the real problem here is missing Flutter 2.13 in pubspec.yaml:

```yaml
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.10.5'
```

**Comment by mark8044** [comment]
Same exact issue for me, for now went back to 0.2.2

**Comment by meg4cyberc4t** [comment]
The same problem. Please fix it 🙏🏻  @alexeyinkin

**Comment by hicnar** [comment]
Same here, back to 0.2.2. Write some tests before releasing your stuff please!

**Comment by meg4cyberc4t** [comment]
> Same here, back to 0.2.2. Write some tests before releasing your stuff please!

Yes, there are tests, but only on flutter 2.10.5 they do not pass)
(Thanks for the temporary solution)

**Comment by hicnar** [comment]
If tests run against the latest stable release do not pass, then why the library gets released one might ask?
Hopefully this will get fixed soon.

**Comment by gysipos** [comment]
+1 for the issue

**Comment by dhanrajVerma** [comment]
facing exactly same issue
+1 for the issue

**Comment by zzterrozz** [comment]
Any solution please?

**Comment by meg4cyberc4t** [comment]
> > Any solution please?
> 
> Just downgrade back to 0.2.2, its not like 0.3.0 has any new feature

My solution was to use scroll_to_index (https://pub.dev/packages/scroll_to_index)

**Comment by alexeyinkin** [comment]
To Google team: I believe [package version retraction](https://dart.dev/tools/pub/publishing#retract) is made just for that. It can be done 7 days after publishing, so 3 days are left.

**Comment by jamesderlin** [comment]
@xster Are you fixing this?

**Comment by meg4cyberc4t** [comment]
@devoncarew Could you help us, please?

**Comment by devoncarew** [comment]
@xster - comment https://github.com/google/flutter.widgets/issues/354#issuecomment-1113998524 seems relevant; perhaps retract the last published version and publish a patch version (0.3.1)?

**Comment by devoncarew** [comment]
There is also no CI on this repo (https://github.com/google/flutter.widgets/issues/360), which seems useful to address.

**Comment by xster** [comment]
Thanks for raising the issue. Sorry for the breakage. The SDK version constraints are indeed not correct. My plan is:

1- Push a 0.3.1 that doesn't change the SDK constraints and that just reverts the latest change on this package.
2- Push a 0.3.2 that re-applies the null safety change and that requires an SDK >= 2.13.
3- Retract version 0.3.0 and force the version resolvers to use a new version.

**Comment by xster** [comment]
`flutter pub get` on your projects should now resolve to a newer version that gets the right code based on your SDK version.

**Comment by jamesderlin** [comment]
> Thanks for raising the issue. Sorry for the breakage. The SDK version constraints are indeed not correct. My plan is:
> 
> 1- Push a 0.3.2 that doesn't change the SDK constraints and that just reverts the latest change on this package. 2- Push a 0.3.3 that re-applies the null safety change and that requires an SDK >= 2.13. 3- Retract version 0.3.0 and force the version resolvers to use a new version.

Don't forget about the other packages in the repository, which have similar breakages (e.g. #361).
