### ISSUE TITLE
Prompt that the Schedulerbinding variable in the plug-in can be null

### ISSUE THREAD

**Issue by xieyuhai** [google/flutter.widgets#368]
## Problem description
positioned_list.dart:311:33: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
     - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) {
                                    ^^^^^^^^^^^^^^^^^^^^

-->
![Uploading image.png…]()

When I add Schedulerbinding.Instance variable (?) After that, the code can run normally

**Comment by UsamaKarim** [comment]
`?` is also not needed

**Comment by xieyuhai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jamesderlin** [comment]
See https://github.com/google/flutter.widgets/issues/366#issuecomment-1126203716.

**Comment by xieyuhai** [comment]
The current plug-in version is 2.10.5. After I added (question mark) to the plug-in source code, it runs normally.

**Comment by xieyuhai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
