### ISSUE TITLE
Flutter 3.0 support

### ISSUE THREAD

**Issue by hs029** [google/flutter.widgets#375]
See this warning:

../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart:439:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart:486:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../../appdev/flutter/.pub-cache/hosted/pub.flutter-io.cn/scrollable_positioned_list-0.2.3/lib/src/positioned_list.dart:312:24: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../appdev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^

**Comment by nbnD** [comment]
You got way through it?

**Comment by jamesderlin** [comment]
You should upgrade to the newest version.  The current version of `package:scrollable_positioned_list` is 0.3.2, not 0.2.3.
