### ISSUE TITLE
ScrollablePositionList return _scrollableListState == null inside PageView

### ISSUE THREAD

**Issue by oseiasmribeiro** [google/flutter.widgets#39]
I can't put a ScrollablePositionList inside a PageView. Returns me an error: ... scrollable_positioned_list.dart ': Failed assertion: line 152 pos 12:' _scrollableListState == null ': is not true.

**Comment by tarobins** [comment]
I was trying to reproduce this problem using this app https://github.com/tarobins/page_list_demo but wasn't able to.  Perhaps you can find the difference between what's in your app that allows you to reproduce the problem and this demo and let me know.  

Thanks

Tom

**Comment by tarobins** [comment]
as an aside, I ran into this while trying the above https://github.com/google/flutter.widgets/issues/43

**Comment by oseiasmribeiro** [comment]
Exactly.  It is the same problem.

**Comment by oseiasmribeiro** [comment]
This issue has been resolved!

**Comment by oseiasmribeiro** [comment]
This issue has been resolved in #231
