### ISSUE TITLE
ScrollablePositionedList: offset and listen offset

### ISSUE THREAD

**Issue by CaiWanFeng** [google/flutter.widgets#415]
Need offset like `ScrollController`'s offset. Can you expose `ScrollController`? This is very useful and I think many people desire.

**Comment by simplenotezy** [comment]
That would be very nice, something we need as well

**Comment by VusDanylo** [comment]
+1

**Comment by quangtuyen1993** [comment]
+1

**Comment by tarobins** [comment]
Please see if changes in #474 and  #472 suit your needs.

**Comment by bringbackthedog** [comment]
> Please see if changes in #474 and #472 suit your needs.

While the `ScrollOffsetListener` partially address the issue, it does not get notified when the `ItemScrollController` moves via a call to `ScrollOffsetListener.jumpTo`
