### ISSUE TITLE
ScrollablePositionedList: Index out of range on a new state

### ISSUE THREAD

**Issue by oseiasmribeiro** [google/flutter.widgets#42]
![Captura de Tela 2019-12-11 às 09 42 09](https://user-images.githubusercontent.com/36827173/70622543-ea021380-1bfa-11ea-8eae-6481c7c96b9e.png)
ScrollablePositionedList in a new state brings the index with value outside current Range. Everything indicates that the index value is the first build.

**Comment by oseiasmribeiro** [comment]
Tarobins, when you make a paging scheme, like in a book, sending the initialScrollIndex always to position 0 the ScrollablePositionedList works perfectly. Now imagine a scenario where I do a words search in a book and by clicking on one of the results the ScrollablePositionedList will build and jump to a specific paragraph; So far so good, after that, I need to navigate to the previous or next chapter, I need to rebuild the state to bring in the new chapter by adding a new value to initialScrollIndex, in that case the initial index that corresponds to the first value of initialScrollIndex, it does not update. If of the itemCount is greater than this index value, not problem, because the range is larger, but if itemCount is smaller then the bug happens.

**Comment by oseiasmribeiro** [comment]
Even using JumpTo gives the same problem.

**Comment by oseiasmribeiro** [comment]
This issue has been resolved!

**Comment by iKrupp** [comment]
@oseiasmribeiro hi! How you resolve it?

**Comment by AurelianTimu** [comment]
How did you solve it? I am experiencing exactly the same issue.

**Comment by iKrupp** [comment]
@AurelianTimu сould you give more information about your solution?

**Comment by oseiasmribeiro** [comment]
I simply upgraded to the latest version of the ScrollablePositionedList widget and it worked. Could you post some code examples showing the error? I can reopen a bug.

**Comment by AurelianTimu** [comment]
@iKrupp 

See the comment I left in #77.

**Comment by vabawen** [comment]
@oseiasmribeiro I got **rangeError** with this code:

```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<int> array1;
  List<int> array2;
  List<int> array;
  int initialIndex;

  @override
  void initState() {
    super.initState();
    array1 = List.generate(30, (index) => index);
    array2 = List.generate(10, (index) => index);
    array = array1;
    initialIndex = 15;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
              child: ScrollablePositionedList.builder(
                initialScrollIndex: initialIndex,
                itemBuilder: (context, index) => Container(
                  alignment: Alignment.bottomCenter,
                  padding: EdgeInsets.symmetric(vertical: 20),
                  child: Text('${array[index]}'),
                ),
                itemCount: array.length,
              )
            ),
            Divider(),
            OutlineButton(
              child: Text('Load array2'),
              onPressed: () {
                setState(() {
                  array = array2;
                  initialIndex = 0;
                });
              },
            ),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by oseiasmribeiro** [comment]
I reopened the problem. Maybe the problem doesn't happen to me anymore because I wrapped the ScrollablePositionedList in a PageView. I will make my code available for you to analyze:
https://drive.google.com/file/d/1P88W7Mr2tA-RSeyJFiOU9Kv_Y_8Xt7oE/view?usp=sharing

**Comment by oseiasmribeiro** [comment]
@vabawen, I don't change the list dynamically as in your example. I use PageView for that! But I did a test with your code and for me the problem also occurs.
