### ISSUE TITLE
why version 0.4.0+2 not publish on pub.dev?

### ISSUE THREAD

**Issue by lzhAndroid** [google/flutter.widgets#433]
why version 0.4.0+2 not publish on pub.dev

**Comment by jamesderlin** [comment]
The issue template specifically requests that you specify which package you're referring to since this repository is the home to multiple packages.

I'll assume that you're asking about `package:visibility_detector`.  I'm not sure why 0.4.0 hasn't been published. @dnfield ?

**Comment by dnfield** [comment]
I don't think I had access. @xster or @devoncarew might

**Comment by devoncarew** [comment]
I do see the last publish as `0.3.3`; it looks like `0.4.0`, `0.4.0+1`, and `0.4.0+2` have not yet been published.

**Comment by dnfield** [comment]
Someone with google.dev pub permissions needs to publish.

**Comment by devoncarew** [comment]
@dnfield, you should have permissions to publish to google.dev packages now (or at least have an invite).

However, this might be a good opportunity to leverage some newer publishing tooling. pub.dev decently added the ability to authorize a github action running on a package's repo to publish that package. So essentially people with commit rights to a repo can publish that package.

I'm just about the land some tooling around that new capability. It'll let you tag a commit w/ a well-formed tag and trigger a publish. So here, tagging commit https://github.com/google/flutter.widgets/commit/9aeb2238a078c670257c8a06f8235e4133e444b6 with `visibility_detector-v0.4.0` would publish that commit as `0.4.0`.

I'll look into integrating that tooling in a day or two. @jamesderlin - I believe you have commit rights to this repo (I have commit rights but am not an admin here)?

**Comment by naamapps** [comment]
Any update on this?

**Comment by dnfield** [comment]
Sorry for the delay. I was on leave when this issue was originally raised and then it fell off my radar when I got back.

Unfortunately, my invitation to join google.dev seems to have expired - I've asked Devon separately to resend it. Once I have that I'll publish.

**Comment by dnfield** [comment]
https://pub.dev/packages/visibility_detector now has 0.4.0+2
