### ISSUE TITLE
ScrollablePositionedList scroll to last index will perform bounse effect

### ISSUE THREAD

**Issue by niuxinghua** [google/flutter.widgets#44]
ScrollablePositionedList scroll to last index will perform bounse effect , indeed we need the list scrollto the end of widget

**Comment by tarobins** [comment]
Are you trying to scroll the last item to the top of the viewport?  It will bounce because the list tries to fill the viewport if possible.

Do you want to be able to:

1) scroll the last item to the top of the viewport and have no bounce?
or 2) scroll the last item to the bottom of the viewport so it won't have to bounce?

**Comment by daibao520** [comment]
same problem
i need 2

**Comment by niuxinghua** [comment]
scroll the last item to the bottom of the viewport so it won't have to bounce is expected

**Comment by Aleafleave** [comment]
> scroll the last item to the bottom of the viewport so it won't have to bounce is expected

how to resolve this problem.

**Comment by JoeyTeng** [comment]
I did a very dirty trick: add a empty `Container` as the last element in the scroll list, and use `jumpTo(index: <the last index>, aligment: 1.0);` to kind of mitigated this issue.

The problem left is the list will not start from the top when the content in the list is not enough to cover the full display space.

**Comment by alen252** [comment]
> I did a very dirty trick: add a empty `Container` as the last element in the scroll list, and use `jumpTo(index: <the last index>, aligment: 1.0);` to kind of mitigated this issue.
> 
> The problem left is the list will not start from the top when the content in the list is not enough to cover the full display space.

It is a solution.
