### ISSUE TITLE
Add Scroll controller ?

### ISSUE THREAD

**Issue by harryandroiddev** [google/flutter.widgets#444]
with this package i am not able to detect the scroll direction of the user as to hide or show something on scroll up or down this can be only possible with the scroll controller which is missing in this package so i request you to add this feature ,to make it more userful .

**Comment by dupovalo** [comment]
Though I'd also like an ability to use direct scroll controller, @harryandroiddev you can look at NotificationListener class in order to achieve your goals (https://api.flutter.dev/flutter/widgets/NotificationListener-class.html).
