### ISSUE TITLE
[feature_request] jumpTo and animateTo feature in Scrollable_positoined_list

### ISSUE THREAD

**Issue by shakilhossain38** [google/flutter.widgets#460]
Fearure request to add jumpTo and animateTo postions along with the jumpToIndex and animateToindex

**Comment by tarobins** [comment]
Sorry, this in infeasible.  We aren't able to compute the the pixel offset of an item until it is on screen, and even then we can only compute pixel offsets if items relative to the position of other items currently on screen (or in the buffer).
