### ISSUE TITLE
VisibilityDetectorController is not visible, because it is not exported.

### ISSUE THREAD

**Issue by bbottema** [google/flutter.widgets#477]
## Problem description

visibility_detector

## Steps to reproduce

```dart
import 'package:visibility_detector/visibility_detector.dart';
// or even 
import 'package:visibility_detector/src/visibility_detector_controller.dart';


VisibilityDetectorController.instance.updateInterval = Duration.zero;
```

Import fails, because VisibilityDetectorController is [not exported](https://github.com/google/flutter.widgets/blob/eb38a4d22b56680afe31694b6dd99e7721a08fd4/packages/visibility_detector/lib/src/visibility_detector_controller.dart#L13).

Btw, this is repeatedly documented as valid use, so it's not like I'm trying to do something I'm not supposed to.

**Comment by jamesderlin** [comment]
Huh?  https://github.com/google/flutter.widgets/blob/master/packages/visibility_detector/lib/visibility_detector.dart clearly shows that `VisibilityDetectorController` is exported.

**Comment by bbottema** [comment]
Yes, I user error, I just discovered. Closing. Sorry.
