### ISSUE TITLE
[visibility_detector] onVisibilityChanged not works when scroll faster 

### ISSUE THREAD

**Issue by user97116** [google/flutter.widgets#529]

**Comment by jamesderlin** [comment]
Details?

**Comment by user97116** [comment]
This code in Single child scroll view when I scroll slowly it works fine no issues, but when I scroll faster it won't works
```dart
    VisibilityDetector(
              key: const ValueKey("item"),
              onVisibilityChanged: (info) {
                print(info);
                if (info.visibleBounds.bottom > 0 &&
                    !onView.isAnimating &&
                    !onView.isCompleted) {
                  onView.forward(from: 0.0);
                } else if (info.visibleBounds.bottom == 0) {
                  onView.reset();
                }
              },
              child: AnimatedBuilder(
                animation: onView,
                builder: (context, snapshot) {
                  return Container(
                    height: 400,
                    color: ColorTween(begin: Colors.amber, end: Colors.red)
                        .evaluate(onView),
                    alignment: Alignment.center,
                    child: Transform.translate(
                      offset: Tween<Offset>(
                        end: Offset.zero,
                        begin: Offset(
                            -MediaQuery.of(context).size.width / 1.5, 100),
                      ).evaluate(onView),
                      child: Container(
                        width: 60,
                        height: 60,
                        decoration: const BoxDecoration(
                          color: Colors.purple,
                          shape: BoxShape.circle,
                        ),
                      ),
                    ),
                  );
                },
              ),
            )
  
```

**Comment by user97116** [comment]
Expect behaviour -> when it visible onVisibiltyChanged it must  called 
Actual behaviour -> when it visible onVisibiltyChanged not called

onVisibilityChanged callback not working when scrolling faster @jamesderlin

**Comment by jamesderlin** [comment]
Can you clarify exactly what "not working" means?  What behavior did you expect to happen, and what behavior did you actually observe?

**Comment by user97116** [comment]
Expect behaviour -> when it visible onVisibiltyChanged it must  called 
Actual behaviour -> when it visible onVisibiltyChanged not called

https://github.com/google/flutter.widgets/assets/35018901/18c97b10-df2e-40e6-8bf2-a2aab4db7668

**Comment by user97116** [comment]
@jamesderlin

**Comment by jamesderlin** [comment]
I'm not exactly sure what I'm supposed to be observing, but if you're complaining that when scrolling quickly such that a hidden `VisibilityDetector` momentarily becomes visible, becomes hidden again, and does not fire any callback, then that's intended behavior. (Conversely, if a `VisibilityDetector` is visible, momentarily becomes hidden, and then becomes visible again, it also will not fire a callback.)

From the `README`:

> Callbacks are not fired immediately on visibility changes. Instead, callbacks are deferred and coalesced such that the callback for each `VisibilityDetector` will be invoked at most once per `VisibilityDetectorController.updateInterval`

You can decrease [`VisibilityDetectorController.updateInterval`](https://pub.dev/documentation/visibility_detector/latest/visibility_detector/VisibilityDetectorController/updateInterval.html) (the default value is 500 ms), even to 0, although decreasing it too much could negatively impact your application performance.
