### ISSUE TITLE
Provider still uses 3.x instead of 4.x

### ISSUE THREAD

**Issue by vanlooverenkoen** [google/flutter.widgets#58]
We updated our project to provider 4.x and now we can't use flutter_widgets. because it still uses 3.x

**Comment by jamesderlin** [comment]
I am confused.  The flutter_widgets package does not use any version of package:provider.

**Comment by vanlooverenkoen** [comment]
I am confused as wel. This is the message I get when adding flutter_widgets to my dependencies.

```
Because flutter_widget >=1.0.10 depends on provider 3.2.0 and my_project depends on provider ^4.0.1, flutter_widget >=1.0.10 is forbidden.

So, because my_project depends on flutter_widget ^1.0.10, version solving failed.
pub get failed (1; So, because my_project depends on flutter_widget ^1.0.10, version solving failed.)
```

**Comment by Rahiche** [comment]
`flutter_widget` is a different package. the correct name is `flutter_widgets`
https://pub.dev/packages/flutter_widgets

**Comment by vanlooverenkoen** [comment]
AHA 😂 😂  that explains :D
