### ISSUE TITLE
VisibilityDetector does not allow to set updateTime

### ISSUE THREAD

**Issue by mishatron** [google/flutter.widgets#61]
It is needed to detect changes after every frame, but updateTime is constantly set to 500ms. Real case: to detect unread messages in chat if user scrolls so fast. Sould be customizable

**Comment by jamesderlin** [comment]
There is no variable named `updateTime`.  Do you mean [`VisibilityDetectorController.updateInterval`](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/VisibilityDetectorController/updateInterval.html)?  That is already configurable and documented.

**Comment by jamesderlin** [comment]
BTW, while 500ms might be too long for your liking, I would not recommend setting `updateInterval` to `Duration.zero` to get updates on every frame, particularly for cases where the user scrolls quickly.  Doing that could inundate you with callbacks, and even if a chat message was visible for a single frame, it is unlikely that the user could have actually read it in 1/60th of a second.

**Comment by mishatron** [comment]
> There is no variable named `updateTime`. Do you mean [`VisibilityDetectorController.updateInterval`](https://pub.dev/documentation/flutter_widgets/latest/flutter_widgets/VisibilityDetectorController/updateInterval.html)? That is already configurable and documented.

I fixed variable name. so for what is recommended to use Duration.zero?

**Comment by jamesderlin** [comment]
You're free to set `updateInterval` to `Duration.zero` if you really want visibility callbacks to fire on every frame.  It's useful for tests.  I just don't personally recommend using that value in a production app since I think it would be overkill, would be too noisy, and wouldn't offer much benefit over using a small but non-zero `Duration`.
