### ISSUE TITLE
[scrollable_positioned_list] Combine with the infinite_listview pacakge

### ISSUE THREAD

**Issue by hanssonduck** [google/flutter.widgets#75]
Is it possible to combine the package with the [infinite_listview](https://pub.dev/packages/infinite_listview#-readme-tab-) package?
The features I'm looking to combine from the packages is the listener of the currently visible items in the list and the infinite scrolling.

Issue in the other package: [#7](https://github.com/fluttercommunity/flutter_infinite_listview/issues/7)

**Comment by tarobins** [comment]
Can you clarify what features you would like added to the ScrollablePositionedList?  

I think some of them might be covered by https://github.com/google/flutter.widgets/issues/46, but I was to know if there are features that wouldn't be.

**Comment by essarn** [comment]
The ability of infinite scrolling in both directions combined with the listener of what items are currently visible.

**Comment by essarn** [comment]
Any updates on this?

**Comment by sabetAI** [comment]
I'm also interested in an update on this issue.

**Comment by jangruenwaldt** [comment]
Would be pretty useful for calendars

**Comment by essarn** [comment]
> Would be pretty useful for calendars

Yes exactly, but switched to KMM and gave up on flutter.
