### ISSUE TITLE
ScrollablePositionedList: calling the builder for an element that has been removed from the array

### ISSUE THREAD

**Issue by iKrupp** [google/flutter.widgets#77]
Hi! If I open the list and put the starting position at the end, and then delete the last element, a situation arises when the widget tries to call the builder for the index, which is already outside the bounds of the array. Is it possible to make the list not look at the starting position and automatically scrolling to the lower border if an empty space appears?

**Comment by iKrupp** [comment]
I seem to have found a similar problem, but one is closed by the author and it is not entirely clear how he solved it.
https://github.com/google/flutter.widgets/issues/42

I would be very happy if you could help me find a way to change the number of elements in the list so that this would not cause problems. (I suppose if the new list has more elements than it was, this should not cause a problem)

**Comment by AurelianTimu** [comment]
Having the same issue.

**Comment by vabawen** [comment]
+1

### Code Sample
```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> titles = [];
  ItemScrollController scrollController = ItemScrollController();

  @override
  void initState() {
    super.initState();
    while(titles.length<30) {
      titles.add('Some Text ${titles.length}');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Expanded(
                child: ScrollablePositionedList.builder(
                  itemScrollController: scrollController,
                  itemBuilder: (context, index) => Container(
                    alignment: Alignment.bottomCenter,
                    padding: EdgeInsets.symmetric(vertical: 10),
                    child: Text(titles[index]),
                  ),
                  itemCount: titles.length,
                )
            ),
            Divider(),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                OutlineButton(
                  child: Text('1.Jump to last item'),
                  onPressed: () {
                    scrollController.jumpTo(index: titles.length-1);
                  },
                ),
                OutlineButton(
                  child: Text('2.Delete the last item'),
                  onPressed: () {
                    titles.removeAt(titles.length-1);
                    setState(() {

                    });
                  },
                ),
              ],
            )
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by AurelianTimu** [comment]
@iKrupp 

I got it working like follows :

I have a variable `_deletedItems` that I use to keep track of the elements that are removed from `entityList`. When an element is removed, I just increment `_deletedItems`.
When `index` becomes equal to  `entityList.length`  and `_deletedItems != 0` it means that an element was removed from the list, hence a `Container()` is returned.

In my case, the code looks something like this  : 
```dart
....

  @override
  void didUpdateWidget(BasePostListView oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.entityList.length > widget.entityList.length) {
      // An item was removed/deleted from the list
        _deletedItems += 1;
    }
    entityList = widget.entityList;
  }
....
itemBuilder: (BuildContext context, int index) {
     if (index <= entityList.length ) {
      final entity = entityList[index];
      return CustomWidget(..); 
    } else if (index == entityList.length && _deletedItems == 0) {
      return CustomWidget(..); 
    } else {
      return Container()
    }
 },
....
```

**Comment by iKrupp** [comment]
@vabawen thank you for example! Could you also duplicate it here: https://github.com/google/flutter.widgets/issues/42

**Comment by iKrupp** [comment]
@AurelianTimu  this was my first thought - returning the stub to an inaccessible index. (for this, it seems, you do not even need to count the number of deleted elements). However, I tried Offstage instead of a container. I will try the container, however this is still a workaround. It would be better if this were fixed on the side of the plugin developers

**Comment by AurelianTimu** [comment]
Correct, you dont need the exact count of deleted items in this case. I am using the count for a different purpose. I forgot to mention it in my comment.
