### ISSUE TITLE
[VisibilityDetector] onVisibilityChanged not triggering when ListView children scrolled into view

### ISSUE THREAD

**Issue by awhitford** [google/flutter.widgets#82]
I tried using `VisibilityDetector` inside a `ListView` thinking that it would trigger when items were scrolled into view, but that didn't reliably work.  😢 

(I'm sorry, but I don't have time to debug this right now; at least, I will record this issue.)

**Comment by jamesderlin** [comment]
This is expected to work.  I can't really do anything with this issue without more details (a reproductoin case would help).  And to confirm, you're aware that there is a delay before `onVisibilityChanged` fires, right?

**Comment by jamesderlin** [comment]
By the way, the demo application does use `VisibilityDetector` within `ListView`s, and it works AFAICT.  Please provide code that can reproduce the problem you're encountering.

**Comment by jamesderlin** [comment]
@awhitford Can you provide more details, please?  Otherwise I am going to close this.

**Comment by jamesderlin** [comment]
Feel free to reopen or re-file if you encounter this again and can provide reproduction steps.
