### ISSUE TITLE
can not get 0.1.3 of scrollable_positioned_list

### ISSUE THREAD

**Issue by jinliyuelong** [google/flutter.widgets#85]
depends on scrollable_positioned_list ^0.1.3 which doesn't match any versions, version solving failed

**Comment by jamesderlin** [comment]
Details, please.  https://pub.dev/packages/scrollable_positioned_list lists version 0.1.3.

I just tried adding:

```
  scrollable_positioned_list: "^0.1.3"
```

to a `pubspec.yaml` file, and `flutter pub get` completed successfully.

**Comment by jamesderlin** [comment]
@jinliyuelong Please provide more details. Otherwise I will close this in a few days.

**Comment by jinliyuelong** [comment]
thank.now it has succeeded
