### ISSUE TITLE
ScrollablePositionedList: Unable to scroll inside Customscrollview

### ISSUE THREAD

**Issue by harasitCS** [google/flutter.widgets#86]
scrollable_positioned_list not scrolling in following view hierarchy.

-----Customscrollview-----
   ---SliverToBoxAdapter---
    child: ScrollablePositionedList.builder

**Comment by jamesderlin** [comment]
It would help a lot of if you could provide sample code that can reproduce the problem.  Thanks!

**Comment by jamesderlin** [comment]
This is a duplicate of https://github.com/google/flutter.widgets/issues/32.
