### ISSUE TITLE
ScrollablePositionedList: expose cacheExtent property

### ISSUE THREAD

**Issue by Zazo032** [google/flutter.widgets#90]
We need this property from `ListView.builder` so items from the list don't get removed.

**Comment by tarobins** [comment]
Need to make minCacheExtent allow for longer "local scrolls"

**Comment by tarobins** [comment]
@Zazo032 do you want to patch in the PR #125 and see if that fixes your issue?

**Comment by tarobins** [comment]
@Zazo032 please check if v 0.1.6 fixes your issue.

**Comment by Zazo032** [comment]
Hey @tarobins, sorry for the late reply, Yes! This is now having our expected behavior, thanks for fixing this up. ✌
