### ISSUE TITLE
Exception thrown when rebuilding the list.

### ISSUE THREAD

**Issue by marcglasberg** [google/flutter.widgets#95]
If I have the `ScrollablePositionedList` with some key, or even inside of some other widget with a key, and then I change the key. I would expect the ScrollablePositionedList  to rebuild and call `initState` again. 

Instead, I am getting this error:

    'package:scrollable_positioned_list/src/scrollable_positioned_list.dart': Failed assertion: line 190 pos 12: '_scrollableListState == null': is not true.

    When the exception was thrown, this was the stack: 
    #2      ItemScrollController._attach (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:190:12)
    #3      _ScrollablePositionedListState.initState (package:scrollable_positioned_list/src/scrollable_positioned_list.dart:225:34)
    #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
    #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
    #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)

**Comment by tarobins** [comment]
I tried to repo with [this project](https://github.com/tarobins/key_change) and a break point in `_ScrollablePositionedListState.initState`.

I hit the breakpoint when I tapped the button and didn't see the exception.  Can you please fork and modify to demo the problem?

**Comment by tarobins** [comment]
Ah.  got it now.

**Comment by tarobins** [comment]
Have fix ^ just need to write a test in the morning

**Comment by tarobins** [comment]
added test.  Will merge soon.
