### ISSUE TITLE
What alignment means for the ScrollablePositionedList should be explained in the docs.

### ISSUE THREAD

**Issue by marcglasberg** [google/flutter.widgets#96]
What `alignment` means for the `ScrollablePositionedList` should be explained in the docs, both for the constructor and for methods like `itemScrollController.jumpTo(index: 10, alignment: 0.0);`

In Flutter, sometimes alignment zero means the center, and then in goes from `-1.0` to `1.0`. In `jumpTo`, alignment goes from `0.0` = top of the screen for vertical non-reversed lists, to `1.0` = bottom of the screen for vertical non-reversed lists.

**Comment by MiguelSOliveira** [comment]
Hey guys, I'm trying to implement tabs with the `ScrollablePositionedList`. My idea is whenever a tab is outside of the view port it will scroll to the viewport. 

If it is outside of the viewport to the right, it will scroll until the rightmost part of the tab is aligned to the right of the screen.
If it is outside of the viewport to the left, it will scroll until the leftmost part of the tab is aligned to the left of the screen.

I don't think this can be done with the alignment property at the moment, but please correct me if I'm wrong.

My question is, will this issue aim to resolve that?

**Comment by jamesderlin** [comment]
This issue is about documentation, not about making any changes to behavior.

You might be interested in https://github.com/google/flutter.widgets/issues/99.

**Comment by MiguelSOliveira** [comment]
Thanks James, I'll try to post there.
